/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;



import org.fusesource.jansi.AnsiConsole;

import com.indvd00m.ascii.render.Render;
import com.indvd00m.ascii.render.api.ICanvas;
import com.indvd00m.ascii.render.api.IContextBuilder;
import com.indvd00m.ascii.render.elements.PseudoText;

import static org.fusesource.jansi.Ansi.*;
import static org.fusesource.jansi.Ansi.Color.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
         // Initialisieren von Jansi
        AnsiConsole.systemInstall();

        // Beispiel für die Verwendung von Jansi
       System.out.println(ansi().fg(YELLOW).a("Hallo").fgBright(GREEN).a(" Welt,").reset());

        System.out.println(
            ansi().fgBright(BLUE).a("DevOps").reset().toString() +
            ansi().fg(RED).a(" vereint").reset().toString() +
            ansi().fg(GREEN).a(" Entwicklung").reset().toString() +
            ansi().fgBright(YELLOW).a(" und").reset().toString() +
            ansi().fg(MAGENTA).a(" Betrieb.").reset().toString()
        );
        System.out.println(
            ansi().fg(CYAN).a("Kollaboration").reset().toString() +
            ansi().fg(MAGENTA).a(" und").reset().toString() +
            ansi().fgBright(BLUE).a(" Kommunikation").reset().toString() +
            ansi().fg(RED).a(" sind").reset().toString() +
            ansi().fgBright(GREEN).a(" essentiell.").reset().toString()
        );
        System.out.println(
            ansi().fgBright(YELLOW).a("Automatisierte").reset().toString() +
            ansi().fg(MAGENTA).a(" Prozesse").reset().toString() +
            ansi().fgBright(CYAN).a(" verbessern").reset().toString() +
            ansi().fg(BLUE).a(" die").reset().toString() +
            ansi().fgBright(RED).a(" Effizienz.").reset().toString()
        );
        System.out.println(
            ansi().fgBright(GREEN).a("Stetige").reset().toString() +
            ansi().fg(YELLOW).a(" Integration").reset().toString() +
            ansi().fg(MAGENTA).a(" und").reset().toString() +
            ansi().fg(CYAN).a(" Bereitstellung").reset().toString() +
            ansi().fg(WHITE).a(" beschleunigen").reset().toString() +
            ansi().fg(BLUE).a(" Updates.").reset().toString()
        );
        System.out.println(
            ansi().fgBright(RED).a("Monitoring").reset().toString() +
            ansi().fgBright(GREEN).a(" und").reset().toString() +
            ansi().fg(YELLOW).a(" Logging").reset().toString() +
            ansi().fgBright(MAGENTA).a(" gewährleisten").reset().toString() +
            ansi().fg(CYAN).a(" Stabilität.").reset().toString()
        );
    
        
        System.out.println(ansi().fg(WHITE).a("Dies ist ein Pseudotext ohne Farbe.").fgBright(GREEN).a(" Oder auch nicht.").reset());

        // Deinstallieren von Jansi
        AnsiConsole.systemUninstall(); 

        Render render = (Render) new Render();
		IContextBuilder builder = (IContextBuilder) render.newBuilder();
		((IContextBuilder) builder.width(120)).height(20);
		builder.element(new PseudoText("PseudoText"));
		ICanvas canvas = render.render(builder.build());
		String s = canvas.getText();
		System.out.println(s);
    
        }

    }

